apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: arm-us-east-2
  version: "1.22"
  region: us-east-2

kubernetesNetworkConfig:
  ipFamily: IPv4

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.10.1-eksbuild.1 # optional
  - name: coredns
    version: v1.8.4-eksbuild.1 # optional
  - name: kube-proxy
    version: v1.21.2-eksbuild.2 # optional


managedNodeGroups:
  - instanceType: "c6g.large"
    amiFamily: AmazonLinux2
    name: arm-ng-1
    desiredCapacity: 1
    maxSize: 4
    minSize: 1
    tags:
      project: coap
    labels:
      project: coap
